=head1 NAME

bitcoinaverage.pl - fetch bitcoin pricing info from api.bitcoinaverage.com

=head1 SYNOPSIS

    Fetch bitcoin pricing info from api.bitcoinaverage.com    
    Prints current 24-hour average, previous 7 days average, 14th, 21st, and 28th previous day average. 

    bitcoinaverage.pl [options]

    Options:
        --primary_currency=     Defaults to USD.
        --local_currency=       Defaults to NZD.


=cut

=head1 LICENSE

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.


=cut

